name: perfect_cyrcle
description: "Draw Perfect Circle - A fun drawing game to test your circle drawing skills"
homepage: https://github.com/orestislef/perfect_cyrcle
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
