name: perfect_cyrcle
description: "Draw Perfect Circle - A fun drawing game to test your circle drawing skills"
homepage: https://github.com/orestislef/perfect_cyrcle
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
#>dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#fef9ee"
    theme_color: "#fef9ee"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
    
#>dart run flutter_native_splash:create
flutter_native_splash:
  color: "#fef9ee"
  image: assets/images/logo.png
  branding_mode: bottom
  color_dark: "#fef9ee"
  image_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#fef9ee"
  web_image_mode: center
